# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUI_pyqt5.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1077, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.DevIp_Label = QtWidgets.QLabel(self.centralwidget)
        self.DevIp_Label.setGeometry(QtCore.QRect(10, 30, 51, 21))
        self.DevIp_Label.setTextFormat(QtCore.Qt.AutoText)
        self.DevIp_Label.setObjectName("DevIp_Label")
        self.DevMask_Label = QtWidgets.QLabel(self.centralwidget)
        self.DevMask_Label.setGeometry(QtCore.QRect(10, 70, 54, 12))
        self.DevMask_Label.setObjectName("DevMask_Label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 30, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 60, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(10, 100, 171, 21))
        self.checkBox.setObjectName("checkBox")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 190, 191, 331))
        self.textEdit.setObjectName("textEdit")
        self.DevList_Label = QtWidgets.QLabel(self.centralwidget)
        self.DevList_Label.setGeometry(QtCore.QRect(20, 160, 121, 21))
        self.DevList_Label.setObjectName("DevList_Label")
        self.addToDevList = QtWidgets.QPushButton(self.centralwidget)
        self.addToDevList.setGeometry(QtCore.QRect(30, 130, 121, 23))
        self.addToDevList.setObjectName("addToDevList")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 20, 131, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 50, 51, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 80, 51, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(230, 110, 51, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 140, 71, 31))
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(370, 20, 221, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(370, 60, 221, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(370, 90, 221, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(370, 120, 221, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(370, 150, 221, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(250, 190, 131, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(400, 190, 131, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(540, 190, 121, 23))
        self.pushButton.setObjectName("pushButton")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(240, 210, 431, 191))
        self.textEdit_2.setObjectName("textEdit_2")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(390, 440, 221, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(390, 500, 221, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(230, 460, 51, 31))
        self.label_6.setObjectName("label_6")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(390, 470, 221, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(230, 430, 121, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(230, 490, 61, 31))
        self.label_8.setObjectName("label_8")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(610, 150, 69, 22))
        self.comboBox.setTabletTracking(False)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 450, 51, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(680, 450, 51, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(620, 20, 51, 31))
        self.label_9.setObjectName("label_9")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(680, 20, 71, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(770, 20, 81, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1077, 23))
        self.menubar.setObjectName("menubar")
        self.menusoft = QtWidgets.QMenu(self.menubar)
        self.menusoft.setObjectName("menusoft")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.actionSaveCardList = QtWidgets.QAction(MainWindow)
        self.actionSaveCardList.setObjectName("actionSaveCardList")
        self.actionLoadDevList = QtWidgets.QAction(MainWindow)
        self.actionLoadDevList.setObjectName("actionLoadDevList")
        self.actionLoadCardList = QtWidgets.QAction(MainWindow)
        self.actionLoadCardList.setObjectName("actionLoadCardList")
        self.actionUpLoad = QtWidgets.QAction(MainWindow)
        self.actionUpLoad.setObjectName("actionUpLoad")
        self.menusoft.addAction(self.action1)
        self.menusoft.addAction(self.actionSaveCardList)
        self.menusoft.addSeparator()
        self.menusoft.addAction(self.actionLoadDevList)
        self.menusoft.addAction(self.actionLoadCardList)
        self.menusoft.addSeparator()
        self.menu.addAction(self.actionUpLoad)
        self.menubar.addAction(self.menusoft.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DevIp_Label.setText(_translate("MainWindow", "设备ip"))
        self.DevMask_Label.setText(_translate("MainWindow", "设备掩码"))
        self.checkBox.setText(_translate("MainWindow", "使用指定的FTP_Server_IP"))
        self.DevList_Label.setText(_translate("MainWindow", "设备列表"))
        self.addToDevList.setText(_translate("MainWindow", "添加至设备列表"))
        self.label.setText(_translate("MainWindow", "板卡名称或powerType"))
        self.label_2.setText(_translate("MainWindow", "bootrom"))
        self.label_3.setText(_translate("MainWindow", "系统软件"))
        self.label_4.setText(_translate("MainWindow", "FPGA"))
        self.label_5.setText(_translate("MainWindow", "自定义类型"))
        self.checkBox_2.setText(_translate("MainWindow", "下载完成后重启单盘"))
        self.checkBox_3.setText(_translate("MainWindow", "下载完成后整机重启"))
        self.pushButton.setText(_translate("MainWindow", "添加至板卡列表"))
        self.label_6.setText(_translate("MainWindow", "用户名"))
        self.label_7.setText(_translate("MainWindow", "自定义FTP server ip"))
        self.label_8.setText(_translate("MainWindow", "密码"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.label_9.setText(_translate("MainWindow", "提测单名"))
        self.pushButton_4.setText(_translate("MainWindow", "下载版本"))
        self.menusoft.setTitle(_translate("MainWindow", "工具配置管理"))
        self.menu.setTitle(_translate("MainWindow", "实用工具"))
        self.action1.setText(_translate("MainWindow", "SaveDevList"))
        self.actionSaveCardList.setText(_translate("MainWindow", "SaveCardList"))
        self.actionLoadDevList.setText(_translate("MainWindow", "LoadDevList"))
        self.actionLoadCardList.setText(_translate("MainWindow", "LoadCardList"))
        self.actionUpLoad.setText(_translate("MainWindow", "UpLoadDevList_config"))

